package com.cloudspace.jindun.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHONE_RECORD.
 */
public class PhoneRecord {

    private Long id;
    private String image;
    private String duration;
    private String userid;
    private String name;
    private String status;

    public PhoneRecord() {
    }

    public PhoneRecord(Long id) {
        this.id = id;
    }

    public PhoneRecord(Long id, String image, String duration, String userid, String name, String status) {
        this.id = id;
        this.image = image;
        this.duration = duration;
        this.userid = userid;
        this.name = name;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
